# Generated by Django 5.0.6 on 2024-05-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseplan',
            old_name='page',
            new_name='course',
        ),
    ]
