# Generated by Django 5.0.6 on 2024-05-20 10:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_rename_page_courseplan_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('lesson', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan', to='learn.lesson')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.step')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
