# Generated by Django 5.0.6 on 2024-07-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_alter_course_content_alter_learnindexpage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learn.lesson'),
        ),
    ]
