# Generated by Django 5.0.6 on 2024-05-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completion_date',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stepprogress',
            name='task_info',
            field=models.TextField(blank=True),
        ),
    ]
