# Generated by Django 5.0.6 on 2024-05-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_lessonprogress_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepprogress',
            options={'verbose_name': 'Step Progress', 'verbose_name_plural': 'Step Progresses'},
        ),
    ]
