# Generated by Django 5.0.6 on 2024-05-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_stepprogress_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='progress',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
